version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/rogierlommers/logrus-redis-hook
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go test -coverprofile=coverage.out
      - run: go tool cover -func=coverage.out
  test:
    pre:
      - go get github.com/mattn/goveralls
    override:
      - go test -v -cover -race -coverprofile=/home/ubuntu/coverage.out
    post:
      - /home/ubuntu/.go_workspace/bin/goveralls -coverprofile=/home/ubuntu/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
